In [2]:
import altair as alt
import pandas as pd

In [31]:
# concat3 sample
concat3_sample = pd.read_csv('../data/concat3_sample/Sheet 2-Table 1.csv',
                              parse_dates = ['between_days'])

concat3_sample

,between_days,DataType,c_uniqueUnitID,latitudeDeployed_DecDeg,longitudeDeployed_DecDeg
0,2011-02-17,Acoustic,2011_BRP_CCB_S1016_Dep20_20110217_PU0205_FD020...,41.941200,-70.28800
1,2011-02-17,Acoustic,2011_BRP_CCB_S1016_Dep20_20110217_PU0206_FD020...,41.877100,-70.25400
2,2011-02-17,Acoustic,2011_BRP_CCB_S1016_Dep20_20110217_PU0207_FD020...,41.894800,-70.44390
3,2011-02-17,Acoustic,2011_BRP_CCB_S1016_Dep20_20110217_PU0208_FD020...,41.933400,-70.18590
4,2011-02-17,Acoustic,2011_BRP_CCB_S1016_Dep20_20110217_PU0209_FD020...,41.950800,-70.39010
5,2011-02-17,Acoustic,2011_BRP_CCB_S1016_Dep20_20110217_PU0211_FD020...,41.971100,-70.47650
6,2011-02-17,Acoustic,2011_BRP_CCB_S1016_Dep20_20110217_PU0212_FD020...,41.993100,-70.22010
7,2011-02-17,Acoustic,2011_BRP_CCB_S1016_Dep20_20110217_PU0213_FD020...,41.876200,-70.34120
8,2011-02-17,Whale,NaN,42.108333,-70.16667
9,2011-02-17,Zooplankton,NaN,41.970000,-70.43000
10,2011-03-04,Acoustic,2011_BRP_CCB_S1016_Dep20_20110217_PU0205_FD020...,41.941200,-70.28800
11,2011-03-04,Acoustic,2011_BRP_CCB_S1016_Dep20_20110217_PU0206_FD020...,41.877100,-70.25400
12,2011-03-04,Acoustic,2011_BRP_CCB_S1016_Dep20_20110217_PU0207_FD020...,41.894800,-70.44390
13,2011-03-04,Acoustic,2011_BRP_CCB_S1016_Dep20_20110217_PU0208_FD020...,41.933400,-70.18590
14,2011-03-04,Acoustic,2011_BRP_CCB_S1016_Dep20_20110217_PU0209_FD020...,41.950800,-70.39010
15,2011-03-04,Acoustic,2011_BRP_CCB_S1016_Dep20_20110217_PU0211_FD020...,41.971100,-70.47650
16,2011-03-04,Acoustic,2011_BRP_CCB_S1016_Dep20_20110217_PU0212_FD020...,41.993100,-70.22010
17,2011-03-04,Acoustic,2011_BRP_CCB_S1016_Dep20_20110217_PU0213_FD020...,41.876200,-70.34120
18,2011-03-04,Whale,NaN,42.108333,-70.16667
19,2011-03-06,Acoustic,2011_BRP_CCB_S1016_Dep20_20110217_PU0205_FD020...,41.941200,-70.28800
20,2011-03-06,Acoustic,2011_BRP_CCB_S1016_Dep20_20110217_PU0206_FD020...,41.877100,-70.25400
21,2011-03-06,Acoustic,2011_BRP_CCB_S1016_Dep20_20110217_PU0207_FD020...,41.894800,-70.44390
22,2011-03-06,Acoustic,2011_BRP_CCB_S1016_Dep20_20110217_PU0208_FD020...,41.933400,-70.18590
23,2011-03-06,Acoustic,2011_BRP_CCB_S1016_Dep20_20110217_PU0209_FD020...,41.950800,-70.39010
24,2011-03-06,Acoustic,2011_BRP_CCB_S1016_Dep20_20110217_PU0211_FD020...,41.971100,-70.47650
25,2011-03-06,Acoustic,2011_BRP_CCB_S1016_Dep20_20110217_PU0212_FD020...,41.993100,-70.22010
26,2011-03-06,Acoustic,2011_BRP_CCB_S1016_Dep20_20110217_PU0213_FD020...,41.876200,-70.34120

In [5]:
# concat_pivot sample (came from concat4 -- condensed acoustic df + whale + zoo)
pivot_sample = pd.read_csv('../data/ConcatPivot_sample/Sheet 2-Table 1.csv',
                              parse_dates = ['between_days'])

pivot_sample

  between_days  acoustic  whale  zooplankton  overlap
0   2011-02-17  acoustic  whale  zooplankton     True
1   2011-03-04  acoustic  whale          NaN    False
2   2011-03-06  acoustic    NaN          NaN    False

`melt pivoted data back to long form`

In [22]:
# melt pivot table (back to long form, bring new overlap column along)
pivot_melt = pd.melt(pivot_sample, id_vars=['between_days','overlap'], 
                     value_vars=['acoustic','whale','zooplankton'])

# don't need 'variable field'
p_melt = pivot_melt[['between_days','value','overlap']]
p_melt

# rename 'value' field to 'DataType'
p_melt = p_melt.rename(columns={'value':'DataType'})

p_melt

  between_days     DataType  overlap
0   2011-02-17     acoustic     True
1   2011-03-04     acoustic    False
2   2011-03-06     acoustic    False
3   2011-02-17        whale     True
4   2011-03-04        whale    False
5   2011-03-06          NaN    False
6   2011-02-17  zooplankton     True
7   2011-03-04          NaN    False
8   2011-03-06          NaN    False

`join p_melt (long df with overlap column) to concat3`

In [33]:
# join pivot_sample to concat3_sample
join = concat3_sample.merge(p_melt, left_on=['between_days','DataType'],
                           right_on=['between_days','DataType'], how='right')

join

,between_days,DataType,c_uniqueUnitID,latitudeDeployed_DecDeg,longitudeDeployed_DecDeg,overlap
0,2011-02-17,acoustic,NaN,NaN,NaN,True
1,2011-03-04,acoustic,NaN,NaN,NaN,False
2,2011-03-06,acoustic,NaN,NaN,NaN,False
3,2011-02-17,whale,NaN,NaN,NaN,True
4,2011-03-04,whale,NaN,NaN,NaN,False
5,2011-03-06,NaN,NaN,NaN,NaN,False
6,2011-02-17,zooplankton,NaN,NaN,NaN,True
7,2011-03-04,NaN,NaN,NaN,NaN,False
8,2011-03-06,NaN,NaN,NaN,NaN,False